
export class Converter {

  static TAG = 'Converter'

  static convertContent(content: string, format: string): string {
    // const doc = new DOMParser().parseFromString(content, "text/xml");
    // const result = tj.gpx(doc);
    // let generator: Generator<F, void, void> | null = null;//用于接受生成器函数返回值
    // generator = tj.tcxGen(doc);
    // const features: F[] = Array.from(generator);//从生成器结果一次性取出存放在feature中

    return ""
  }

}